### ISSUE TITLE
Running Docker Local, use logs to determine when container is up

### ISSUE THREAD

**Issue by rbarcia** [ibm-cloud-architecture/refarch-cloudnative-micro-socialreview#2]
I tried to push update to readme, it says I am not authorized.  Please change my level as exec sponsor.   

for all Docker run local, please add 

docker ps (see container s running, note container id)
docker logs {container-id} to see springboot logs to wait app is started.

**Comment by gangchen03** [comment]
Fixed the doc as suggested, close ticket.
