### ISSUE TITLE
Us $(cf ic namespace get) like you did in inventory

### ISSUE THREAD

**Issue by rbarcia** [ibm-cloud-architecture/refarch-cloudnative-micro-socialreview#3]
Tried to update instructions,

new-host-3:refarch-cloudnative-micro-socialreview Roland$ git push
remote: Permission to ibm-cloud-architecture/refarch-cloudnative-micro-socialreview.git denied to rbarcia.
fatal: unable to access 'https://github.com/ibm-cloud-architecture/refarch-cloudnative-micro-socialreview/': The requested URL returned error: 403
new-host-3:refarch-cloudnative-micro-socialreview Roland$

**Comment by gangchen03** [comment]
Please accept git invitation: https://github.com/ibm-cloud-architecture/refarch-cloudnative-micro-socialreview/invitations

**Comment by gangchen03** [comment]
Issue has been addressed, will be in the r1 master after integration test.
